### ISSUE TITLE
example in readme not work

### ISSUE THREAD

**Issue by maicWorkGithub** [digidem/osm2obj#9]
```
var fs = require('fs')
var path = require('path')
var Osm2Obj = require('osm2obj')

var rs = fs.createReadStream(path.join(__dirname, './aa.xml'))

rs.pipe(new Osm2Obj()).pipe(process.stdout)
```

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:258:10)
    at Socket.Writable.write (_stream_writable.js:292:21)
    at Osm2Obj.ondata (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at Osm2Obj.emit (events.js:182:13)
    at addChunk (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Osm2Obj.Readable.push (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Osm2Obj.Transform.push (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at Osm2Obj._transform (c:\Users\NCU\workspace\react-test\node_modules\osm2obj\lib\osm2obj.js:113:34)
    at Osm2Obj.Transform._read (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_transform.js:184:10)
Emitted 'error' event at:
    at Socket.onerror (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at Socket.emit (events.js:182:13)
    at validChunk (_stream_writable.js:261:12)
    at Socket.Writable.write (_stream_writable.js:292:21)
    [... lines matching original stack trace ...]
    at Osm2Obj.Transform.push (c:\Users\NCU\workspace\react-test\node_modules\readable-stream\lib\_stream_transform.js:148:32)
```

`node: 10.14.2`

**Comment by hackergrrl** [comment]
Oh hey, you're right: that's a totally bad example in the readme! This is because osm2obj is an object stream, whereas stdout is a binary stream. Try this instead:

```js
var fs = require('fs')
var Osm2Obj = require('../lib/osm2obj')

var rs = fs.createReadableStream(__dirname + './osm.xml')

rs.pipe(new Osm2Obj())
  .on('data', console.log)
```

**Comment by maicWorkGithub** [comment]
Thanks!
